// packages/react-ui/src/Button.tsx
import React from 'react';
import './Button.scss';

export interface ButtonProps {
  variant?: 'primary' | 'secondary' | 'success' | 'warning' | 'error';
  size?: 'sm' | 'md' | 'lg';
  disabled?: boolean;
  type?: 'button' | 'submit' | 'reset';
  onClick?: (event: React.MouseEvent<HTMLButtonElement>) => void;
  children: React.ReactNode;
}

export const Button: React.FC<ButtonProps> = ({
  variant = 'primary',
  size = 'md',
  disabled = false,
  type = 'button',
  onClick,
  children,
  ...props
}) => {
  const buttonClasses = [
    'qk-button',
    `qk-button--${variant}`,
    `qk-button--${size}`,
    disabled ? 'qk-button--disabled' : ''
  ].filter(Boolean).join(' ');

  return (
    <button
      className={buttonClasses}
      disabled={disabled}
      type={type}
      onClick={onClick}
      {...props}
    >
      {children}
    </button>
  );
};

// packages/angular-ui/src/lib/button/button.component.ts
import { Component, Input, Output, EventEmitter, input, output, computed } from '@angular/core';

export type ButtonVariant = 'primary' | 'secondary' | 'success' | 'warning' | 'error';
export type ButtonSize = 'sm' | 'md' | 'lg';

@Component({
  selector: 'qk-button',
  standalone: true,
  template: `
    <button 
      [class]="buttonClasses()" 
      [disabled]="disabled()"
      (click)="onClick.emit($event)"
      [type]="type()">
      <ng-content></ng-content>
    </button>
  `,
  styleUrls: ['./button.component.scss']
})
export class ButtonComponent {
  // Using new Angular 20 signal-based inputs
  variant = input<ButtonVariant>('primary');
  size = input<ButtonSize>('md');
  disabled = input<boolean>(false);
  type = input<'button' | 'submit' | 'reset'>('button');
  
  // Using new Angular 20 signal-based outputs
  onClick = output<Event>();

  // Computed signal for button classes
  buttonClasses = computed(() => {
    const classes = [
      'qk-button',
      `qk-button--${this.variant()}`,
      `qk-button--${this.size()}`
    ];
    
    if (this.disabled()) {
      classes.push('qk-button--disabled');
    }
    
    return classes.join(' ');
  });
}
