// apps/quanta-kit-vue-docs/src/App.vue
<template>
  <div id="app">
    <img
      alt="Vue logo"
      src="./assets/logo.png"
    >
    
    <h1>Quanta Kit Vue Documentation</h1>
    <p>Welcome to the Quanta Kit Vue component library documentation.</p>
    
    <section style="margin: 2rem 0;">
      <h2>Button Component Examples</h2>
      
      <div style="display: flex; gap: 1rem; justify-content: center; flex-wrap: wrap; margin-bottom: 1rem;">
        <QkButton
          variant="primary"
          @click="handlePrimaryClick"
        >
          Primary Button
        </QkButton>
        <QkButton
          variant="secondary"
          @click="handleSecondaryClick"
        >
          Secondary Button
        </QkButton>
        <QkButton
          variant="outline"
          @click="handleOutlineClick"
        >
          Outline Button
        </QkButton>
        <QkButton
          variant="ghost"
          @click="handleGhostClick"
        >
          Ghost Button
        </QkButton>
      </div>
      
      <div style="display: flex; gap: 1rem; justify-content: center; flex-wrap: wrap; margin-bottom: 1rem;">
        <QkButton size="small">
          Small Button
        </QkButton>
        <QkButton size="medium">
          Medium Button
        </QkButton>
        <QkButton size="large">
          Large Button
        </QkButton>
      </div>
      
      <div style="display: flex; gap: 1rem; justify-content: center; flex-wrap: wrap;">
        <QkButton disabled>
          Disabled Button
        </QkButton>
        <QkButton
          variant="primary"
          type="submit"
        >
          Submit Button
        </QkButton>
      </div>
    </section>
  </div>
</template>

<script>
import { Button as QkButton } from 'quanta-kit-design-system-vue'

export default {
  name: 'App',
  components: {
    QkButton
  },
  methods: {
    handlePrimaryClick() {
      alert('Primary button clicked!')
    },
    handleSecondaryClick() {
      alert('Secondary button clicked!')
    },
    handleOutlineClick() {
      alert('Outline button clicked!')
    },
    handleGhostClick() {
      alert('Ghost button clicked!')
    }
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// apps/quanta-kit-react-docs/src/app/page.tsx
"use client";

import Image from "next/image";
import styles from "./page.module.css";
import { Button } from "quanta-kit-design-system-react";

export default function Home() {
  return (
    <div className={styles.page}>
      <main className={styles.main}>
        <Image
          className={styles.logo}
          src="/next.svg"
          alt="Next.js logo"
          width={180}
          height={38}
          priority
        />

        <h1>Quanta Kit React Documentation</h1>
        <p>Welcome to the Quanta Kit React component library documentation.</p>

        <section style={{ margin: "2rem 0" }}>
          <h2>Button Component Examples</h2>
          <div
            style={{
              display: "flex",
              gap: "1rem",
              flexWrap: "wrap",
              marginBottom: "1rem",
            }}
          >
            <Button variant="primary" onClick={() => alert("Primary clicked!")}>
              Primary Button
            </Button>
            <Button
              variant="secondary"
              onClick={() => alert("Secondary clicked!")}
            >
              Secondary Button
            </Button>
            <Button variant="outline" onClick={() => alert("Outline clicked!")}>
              Outline Button
            </Button>
            <Button variant="ghost" onClick={() => alert("Ghost clicked!")}>
              Ghost Button
            </Button>
          </div>

          <div
            style={{
              display: "flex",
              gap: "1rem",
              flexWrap: "wrap",
              marginBottom: "1rem",
            }}
          >
            <Button size="small">Small Button</Button>
            <Button size="medium">Medium Button</Button>
            <Button size="large">Large Button</Button>
          </div>

          <div style={{ display: "flex", gap: "1rem", flexWrap: "wrap" }}>
            <Button disabled>Disabled Button</Button>
            <Button variant="primary" type="submit">
              Submit Button
            </Button>
          </div>
        </section>
        <ol>
          <li>
            Get started by editing <code>src/app/page.tsx</code>.
          </li>
          <li>Save and see your changes instantly.</li>
        </ol>

        <div className={styles.ctas}>
          <a
            className={styles.primary}
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              className={styles.logo}
              src="/vercel.svg"
              alt="Vercel logomark"
              width={20}
              height={20}
            />
            Deploy now
          </a>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.secondary}
          >
            Read our docs
          </a>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image
            aria-hidden
            src="/file.svg"
            alt="File icon"
            width={16}
            height={16}
          />
          Learn
        </a>
        <a
          href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image
            aria-hidden
            src="/window.svg"
            alt="Window icon"
            width={16}
            height={16}
          />
          Examples
        </a>
        <a
          href="https://nextjs.org?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image
            aria-hidden
            src="/globe.svg"
            alt="Globe icon"
            width={16}
            height={16}
          />
          Go to nextjs.org →
        </a>
      </footer>
    </div>
  );
}
